### PR TITLE
React.js integration

### PR DESCRIPTION
**Pull request by a-ignatov-parc**
- [x] Implement `style` tag support.
- [x] Unmount components when `document` is removed from rendering stack.
- [x] Implement component's updates.
- [x] Remove everything related to `virtual-dom` lib. We don't need this anymore.
- [x] Implement rendering to modals.
- [x] Implement `menuItem` support.
- [x] Implement proper `menu-button-press` event support.
- [x] Check that navigational hooks are working properly.
- [x] Treat `style` prop as object for better consistency with other react renderers (dom and native).
- [x] Add support for boolean attributes like `autoHighlight`. So there will be no need to provide string values for them. Example: `<menuItem route="my" autoHighlight />`.
- [x] Update `README.md`.
- [x] Implement `dataItem` support.
- [ ] Update [`tvdml-app-boilerplate`](https://github.com/a-ignatov-parc/tvdml-app-boilerplate).

### CODE REVIEW

**Comment by spunkedy** [comment]
How'd this work out ? The only reason I don't use the react tvOS implementation is that it can't render the nice templates that are built in. ( to my knowledge )

**Comment by a-ignatov-parc** [comment]
For now everything forks great. Also integration with redux and other libs works as expected. Need to test some edge cases and integrate with routing. I’m planning to release new major release in two weeks or less 😉

**Comment by a-ignatov-parc** [comment]
You can check my experiments in this PR https://github.com/a-ignatov-parc/tvos-soap4.me/pull/36

**Comment by spunkedy** [comment]
Awesome sauce

**Comment by spunkedy** [comment]
yay

**Pull request merged**
